### ISSUE TITLE
Spine json file format import and export (so you/others dont have to implement a new runtime for each game engine in order to use coa-tools with it)

### ISSUE THREAD

**Issue by blurymind** [ndee85/coa_tools#6]
Advantages of implementing a spine json export in coa tools:
- in one hit , coa-tools animation will become available to all these game engines and more:
  http://esotericsoftware.com/spine-runtimes
  spine is the most supported runtime atm.
- Coa tools Mesh deformation will become available to all these 2d game engines that are not capable of importing fbx.
- Doing mesh deformation in json is cheaper than with fbx.
- Godot already is getting support for importing spine json files, so you wont have to develop and support your own godot importer
- Until you have a run time in the game engine that supports your json file's file structure, you have no advantage of coa tools for doing the animation. For a long time coa tools will be exclusive to only godot's userbase, until people write runtimes for its json structure. By making a spine exporter, you save a lot of people a lot of effort.

Advantages for import:
- There are many spine json exporters already made for the majority of graphics software. There is one for gimp, photoshop, and
  Here i found a similar addon for inkscape that exports json for spine 2d
  https://github.com/jleclanche/inkscape-spine-exporter

Advantages:
-You wont have to reimplement and support yet another runtime in all these game engines in order to use coa tools. Currently there is a diplicated effort to support different structured json file formats that do the exact same things in spriter, spine, creature 2d, and so on. This creates needless extra work for all the game devs to make different runtimes and cuts off a lot of the animators from actually using the tool on a game.
![standards](https://cloud.githubusercontent.com/assets/6495061/13985111/9eec88da-f0f2-11e5-993a-4bd8d0284398.png)

Your exporter already writes to a json file, you just have to change the way it structures the information and stub all the missing features that are not supported yet.
This could of course be done as a new exporter and does not have to overwrite the current one.
I wonder how hard would it be to port it over to do a spine json file

EDIT: Now dragonbones can export to spine. Dragonbones is free. However depending on the game engine you decide to use- if the runtime was written by Esoteric, you may have to buy a spine2d license in order to use spine animation in it.

Coa tools can now export to dragonbones and from there you can use the dragonbones editor to convert the file to spine2d

Here is a list of game engines which support loading spine2d animation files and provide their own runtimes, thus NO need to purchase the 300$ spine2d license:
- Construct2 - https://github.com/flyover/spine-c2-plugin (MIT license)
- Defold - http://forum.defold.com/t/dragon-bones-4-9-5-supports-spine-3-3/3630/6

runtimes that need to be researched:
- Game maker by yoyo games - https://forum.yoyogames.com/index.php?threads/gamemaker-and-spine-runtime.9609/

If you think of any others, please post here

**Comment by diramazioni** [comment]
yes! looks like exists also for [GIMP](https://gist.github.com/NathanSweet/fa1626385bb3570d2552)

**Comment by andeon** [comment]
For GIMP this looks better [https://github.com/andeon/gimp-spine](url)

**Comment by ndee85** [comment]
Maybe a good solution would be to not write a custom exporter for each image editing programm, but instead write an importer at exported spine files from image editing programms. Will need to take a look at it.

**Comment by andeon** [comment]
@ndee85 Sounds good! Will facilitate the access and take advantage of what is already done.

Awesome job here! :)

**Comment by blurymind** [comment]
@ndee85 this is a fantastic idea. Spine json animation file is currently the most widely supported across game engines. If you write an exporter, coa_tools will become available to all the game engines that have run times for spine. That includes:
http://esotericsoftware.com/spine-runtimes

You will hit quite a lot of rabbits with one rock.
Also spine's json files include skinned mesh data support - deforming sprites.

**Comment by NathanLovato** [comment]
Yeah, that would be a great idea - the numerous developers who use Spine would then be able to switch to the COA tools ;)

**Comment by blurymind** [comment]
Spine is also natively supported in game maker. Other engines not mentioned in above link include construct2. Looking at the license i couldnt find any clause that prohibits the export to spine json file format. 
http://esotericsoftware.com/forum/Runtimes-LICENSING-4984

**Comment by blurymind** [comment]
yes, it will solve that issue entry as well!   :) 
I am quite sure that adding support to it would automatically attract A LOT of more people to coa-tools. 

Let me know if you need any help investigating this :+1:  I am quite excited about it because it will bring coa tools to a plethora of game engines elegantly

**Comment by andeon** [comment]
@blurymind if want create workflow with linux the .json need looks like with:
https://github.com/ndee85/coa_tools/blob/master/Sample%20Files/stip/stip.json

I found this [script](https://github.com/ray-hplus/inkscape-animation) to inkscape has many option, it's apparently more easy to adapt that the previous option or maybe start a new code if you know python.

Check the line 97 [# create json data ](https://github.com/ray-hplus/inkscape-animation/blob/master/iaps_exanimbatch.py)
the output file https://youtu.be/uzfAX1_MR9w?t=3m46s

If you decide to adapt scripts based on "spine" need check code where have compensate " y and x axis" maybe needs remove it.

To GIMP [Import GIMP Image to Scene (.xcf, .xjt)](https://wiki.blender.org/index.php/Extensions:2.6/Py/Scripts/Import-Export/GIMPImageToScene) maybe can help in the workflow.

We need wait Andreas make COA stable, but Id like to see him set the initial document about ".json data sprite importer" it can help the community create components to other programs, while "spine json" is not defined.

I'm quite excited about COA Tools because it is more one piece of workflow to make animation 2d with blender and can see works with another piece [lipsync papagayo](https://github.com/andeon/lipsync-importer-morevna)

**Comment by blurymind** [comment]
Here is some research on spine. Here is a list of runtimes:
http://esotericsoftware.com/spine-runtimes
They support love2d and a number of other open source engines, mixed with the majority of the most mainstream ones. 

Godot devs are going to be implementing spine2d animation node. There is even code that implements it already:
https://github.com/godotengine/godot/pull/1734

So if you get coa tools to export to spine, you wont have to continue maintaining godot coa tools importer any more. It is also likely that once in godot, spine node will get more developer attention since spine is more widely used.

This page explains the spine json file format:
http://esotericsoftware.com/spine-json-format
example Json file: http://esotericsoftware.com/spine/files/example.json

It seems pretty straightforward. :)

**Comment by blurymind** [comment]
I also uploaded stip's json file with animation included - so as to be able to compare the structure to spine's:

coa tools export (with animation):
https://gist.github.com/blurymind/92566dd333bf869d4eeb

and this is spine's:
http://esotericsoftware.com/files/example.json

**Comment by blurymind** [comment]
You can also download a trial of spine here:
http://esotericsoftware.com/spine-download

**Comment by ndee85** [comment]
@blurymind 
Is there also an example where spine meshes are integrated. It seems this is a simple sprite export. So no meshes as I see from the json file.

**Comment by blurymind** [comment]
hi, sorry.
You can find some example spine files in a pull request to add spine animation in godot here:
https://github.com/sanikoyes/godot/tree/Pr-spine-support-for-godot/demos/2d/spine/spine

Apart of the example files, the repository has code to add spine runtime to godot:
https://github.com/sanikoyes/godot/tree/Pr-spine-support-for-godot

**Comment by blurymind** [comment]
the hero example has a heromesh.json:

https://github.com/sanikoyes/godot/tree/Pr-spine-support-for-godot/demos/2d/spine/spine/hero

here is the file
https://github.com/sanikoyes/godot/blob/Pr-spine-support-for-godot/demos/2d/spine/spine/hero/hero-mesh.json

**Comment by blurymind** [comment]
Another place for example files is their github repository:
https://github.com/EsotericSoftware/spine-runtimes

Each runtime has a folder with an example file. Unity's seems to have the most:
https://github.com/EsotericSoftware/spine-runtimes/tree/master/spine-unity/Assets/Examples/Spine

**Comment by blurymind** [comment]
the velocihorn example is pretty good too:
https://www.youtube.com/watch?v=orqb4Hz4rqI
http://esotericsoftware.com/files/projects/IK-example.zip
http://esotericsoftware.com/files/projects/velocihorn_WIP.zip

**Comment by blurymind** [comment]
creature2d's developer is working on a runtime for godot that adds sprite deformation
https://github.com/kestrelm/Creature_Godot/tree/master/creaturegodot

> Hello all,
> 
> One last update for tonight. I have an initial version built through for Godot:
> https://github.com/kestrelm/Creature_Godot/tree/master/creaturegodot
> 
> This is completely untested but it compiles and links just fine. I can also add it into the editor in Godot Engine.
> I haven’t tested the display yet of course, will do so soon.
> 
> Can you please have a look, the relevant files are:
> 
> creaturegodot.cpp
> creaturegodot.h
> 
> Can you tell me if what I am doing makes sense?
> 
> Cheers

perhaps it would be also good to look into his implementation.

**Comment by blurymind** [comment]
I think we might have a problem here. The runtime license for spine allows you to use said runtime only if you own a spine license- thus buy spine. Same for creature, same for spriter.

So it would really be best if coa tools has it's own file type/runtime. :(

Sadly there is not one open file standard that does this. 
We could keep looking at how the competition does it:
http://www.kestrelmoon.com/creaturedocs/Game_Engine_Runtimes_And_Integration/Runtimes_Introduction.html

**Comment by blurymind** [comment]
Ok I am scrapping this idea because of the license issue with spine runtimes. Instead of spine, we can use dragonbones:
https://github.com/ndee85/coa_tools/issues/26

It's well established, documented, has the runtimes for the game engines and most of all - is open source. If coa_tools exports to dragonbones, it will work with Unity,cocos,and many other game engines.

**Comment by IBwWG** [comment]
@blurymind Citation needed...where do you see this about spriter runtimes needing you to buy spriter?  Most (all?) of the [spriter runtimes](https://brashmonkey.com/spriter-api/) are open source.  The CPP implementation doesn't say anything about needing to own spine: https://github.com/lucidspriter/SpriterPlusPlus/blob/master/LICENSE  Same with .NET: https://github.com/loodakrawa/SpriterDotNet/blob/master/LICENSE 

Compared with DragonBones I think spriter has much better runtime support.  I'm not sure about meshes.

**Comment by blurymind** [comment]
Spriter runtime has no support for meshes (dragon bones does). Also it's
runtime is not as mature and supports a smaller number of game engines.
They had changed their entire runtime twice so far and when the mesh
feature is added in spriter 2, they will probably change it again.

Dragonbones seems to have a more active development and better documented
json specification (see link I provided).

**Comment by blurymind** [comment]
in any case, it's to whoever has the skill to actually add the export
feature to coa tools which one is used.

I personally own a spriter license and i know all too well that meshes will
probably not come this year to the runtime , and its possible we dont see
that added next year.
It's a very slow development with only two guys working on it.

it's perhaps best to contact them and see how they feel about other
software supporting their format.

**Comment by rosshadden** [comment]
@blurymind I agree wholeheartedly that exporting to dragonbones makes a lot more sense as the main output of this project.  But I think it would be a good idea to have both.  As you said in your OP, it would drastically broaden the reach of this project.  Instead of supporting ~4 engines we would support ~40.

It's easy to say people should use dragonbones (and I really want it to get to a place where that's possible), but in reality most devs in this space are probably using spine right now, because there are hardly any dragonbones runtimes.  Plus the spine runtimes are _really_ good.  Like the quality of them is much higher than I ever expected.

I have not dropped the $300, and am not sure if I will or if I will ultimately make a dragonbones runtime for the engine I'm using, but regardless devs having options is nice where possible/practical.  It's also worth noting that the $300 is necessary for public releases and distribution, but not to just hack on projects.

**Comment by manuelsongokuh** [comment]
in blender with coatool not worj import from spine json..or there is exaplin how does work in blender with coatool?

**Comment by blurymind** [comment]
As stated in the other thread- supporting spine format is not possible
largely due to spine devs, who have locked it via aggressive licensing.

If you want a good open alternative, just advocate for dragonbones and
promote its use. One way or another it also will get a runtime for your
favorite game engine. You or someone else has to just sit down and write
it. Request it from dragonbones devs too- they might do it if the engine is
popular enough :)

**Comment by rosshadden** [comment]
@blurymind Everything you said in the other thread (conversing about it here makes more sense---my bad) is completely fair and I agree.  In fact a couple of hours before I commented here, [I asked Dragonbones about love/lua suspport](https://twitter.com/darthlink44/status/800905943517040642).

The thing is, from my perspective Dragonbones has several big things going against it for now.  The biggest is that it is for some reason written with Adobe Air, which baffles me because I thought people stopped using that a decade ago.  This is a problem because the version they use does not and will never run on linux, so thus their editor [doesn't work on linux](https://github.com/DragonBones/DesignPanel/issues/31).  That's why I came here, by the way, so I can use it anyway.  The other problem, as I said, are the lack of runtimes.  I completely agree with you that we can and should advocate for some sort of open alternative to Spine/Spriter.

To be honest I don't have all that much faith in Dragonbones as that alternative because in alienating Linux they are alienating the largest demographic likely to actually jump in and dump a fair bit of effort and make many commits to such a tool.  But in reality it is the only one right now, so advocating for it is better than remaining silent.

My thought in suggesting coa_tools export to Spine as well is that people might come here because Blender is _very_ powerful, and with this tool has the potential to be _better_ than spine/spriter/dragonbones/etc.  I can foresee a possible future in which people want to use Blender+coa_tools even over whichever proprietary tools they may have access to.  And in my emails with Spine (where I asked for a lot of clarification on their license restrictions because I was terrified of them (turns out it's not that restrictive at all)) it was clear that they don't mind people using other tools like this but paying for the spine runtimes.  They are aware of it, and that's actually the reason they make people to pay for the runtimes.  Otherwise people would just use something like this and they would never make money.

Anyway, I'm done with my rant.  Hopefully you understand my perspective, even if you don't come to the same conclusions.  Thanks for the conversation!

**Comment by blurymind** [comment]
I have reopened the issue because of recent developments with Defold and Dragonbones.

It seems that it is ok to create spine json animation, without owning a spine license. Using it in a game engine may or may not require you to own the spine license, depending on wether the runtime was developed by esoteric software or not.

With the case of the defold engine - you do not need to own the spine license - you can use the Dragonbones animation editor to export spine json data and run it in defold - for free.

**Comment by blurymind** [comment]
I added a list of engines to the first post , whose spine2d run time does not require one to purchase spine in order to use the animation data
