### ISSUE TITLE
can't "cut out" in edit mesh mode

### ISSUE THREAD

**Issue by diramazioni** [ndee85/coa_tools#9]
First congratulation for this brilliant addon.
I have some serious usability issues to successfully cut-out the contour of the mesh in edit mode. 

1. I've noticed that the cursor change to a "brush" mode and everywhere I click, also on the coa buttons in the toolshelf, a new point get added, so I can't select any option, (like merge vertices) without inserting a new point, I have to Ctrl z

2. I've never been able to successfully create a grid, it says that it's not closed, even if it is. Maybe it fails because a last and isolated point got added when I press Triangle Fill (because of point 1)

3.  When it fails there is no way back, I have to delete the sprite and reimport it and try to edit the mesh again

4. It's impossible to select a single vertex if you have "select with left" in user pref. The tool behave differently adding point by dragging in this mode. I use a tablet so when I touch the pen to the surface is read as left click (it's a very clumsy workflow to have select with right with this setup), Anyway I've tried also with a mouse and select with right, but still the problem of the extra vertex described above remains and I can't grid fill

Hope these problems get ironed out from a great beta version, maybe it's me missing something?
edit: (I'm using the latest version here on github and I've tried with both 2.76b and 2.77rc2)

**Comment by ndee85** [comment]
thanks for this report. ok, I think most of this is related to the left right switch in blender. I tried a fix now. The only way to fix this is to also switch paint and drag button once it is switched in the preferences. This is stupid, but I don't see a different solution right now. Blenders event system is strange because of that right left switch. So you have to draw the contour with right click and the bones with right click too. The rest should work. 
The triangulate fill is fixed now too. If a loop is not closed it will just give the message and leave the rest as it is.
Please test and report back. If nothing comes I will close this issue in a few days.

**Comment by diramazioni** [comment]
Yes Yes !!!! works great! good job!!!

**Comment by ndee85** [comment]
great. will set this as closed than!
